import "./../sass/main.scss"
import Footer from "./_components/Layout/Footer"
import Header from "./_components/Layout/Header"
import { AuthProvider } from '../context/AuthContext';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header/>
          {children}
          <Footer/>
        </AuthProvider>
        </body>
    </html>
  )
}
