import "./../sass/main.scss"
import Footer from "./_components/Layout/Footer"
import Header from "./_components/Layout/Header"
import { AuthProvider } from '../context/AuthContext';

export const metadata = {
  title: "Sastrugus - a workshop platform",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="antialiased text-canvas-900 bg-canvas-50 dark:bg-canvas-dark dark:text-gray-100">
        |<AuthProvider>
        <Header/>
        {children}
        <Footer/>
        </AuthProvider>
        </body>
    </html>
  )
}
